name: Build QMK firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      fail-fast: false

    steps:

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v4.2.0
      with:
        repository: qmk/qmk_firmware
        submodules: recursive

    - name: Checkout userspace
      uses: actions/checkout@v4.2.0
      with:
        path: keyboards/crkbd/keymaps/qmk-keymap-corne

    - name: Build firmware
      run: qmk compile -kb crkbd/rev1 -km qmk-keymap-corne -e CONVERT_TO=rp2040_ce

    - name: Archive firmware
      uses: actions/upload-artifact@v4.4.0
      continue-on-error: true
      with:
        path: |
          *.hex
          *.bin
          *.uf2
